//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.DataAccess.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limit
    {
        public int LimitID { get; set; }
        public string PlaneType { get; set; }
        public int SpeedStart { get; set; }
        public int SpeedFinish { get; set; }
        public int DistanceStart { get; set; }
        public int DistanceFinish { get; set; }
    }
}
