//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.DataAccess.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public int PlaneID { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public int Speed { get; set; }
    }
}
