//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.DataAccess.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteID { get; set; }
        public string Start { get; set; }
        public string Finish { get; set; }
        public int Distance { get; set; }
    }
}
